return {
  -- fix notify background_colour for oh-my-monokai
  {
    "rcarriga/nvim-notify",
    opts = {
      background_colour = "#000000",
    },
  },
  {
    "justinsgithub/oh-my-monokai.nvim",
    opts = {
      transparent_background = true,
      palette = "justinsgithub",
    },
  },
  -- Configure LazyVim to load custom colorscheme
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "oh-my-monokai",
    },
  },
  { "ChristianChiarulli/nvcode-color-schemes.vim", enabled = true },
  { "Mofiqul/vscode.nvim", enabled = true },
  { "Yazeed1s/oh-lucy.nvim", enabled = true },
  { "andersevenrud/nordic.nvim", enabled = true },
  { "ellisonleao/gruvbox.nvim", enabled = true },
  { "gbprod/nord.nvim", enabled = true },
  { "sainnhe/gruvbox-material", enabled = true },
  { "shaeinst/roshnivim-cs", enabled = true },
  { "tomasiser/vim-code-dark", enabled = true },
  -- ALL THE COLORS (just uncomment)
  -- { "EdenEast/nightfox.nvim", enabled = true },
  -- { "Everblush/everblush.nvim", enabled = true },
  -- { "FrenzyExists/aquarium-vim", enabled = true },
  -- { "Mofiqul/adwaita.nvim", enabled = true },
  -- { "Mofiqul/dracula.nvim", enabled = true },
  -- { "NTBBloodbath/doom-one.nvim", enabled = true },
  -- { "PHSix/nvim-hybrid", enabled = true },
  -- { "RishabhRD/gruvy", enabled = true },
  -- { "Th3Whit3Wolf/one-nvim", enabled = true },
  -- { "Th3Whit3Wolf/space-nvim", enabled = true },
  -- { "Yazeed1s/minimal.nvim", enabled = true },
  -- { "adisen99/apprentice.nvim", enabled = true },
  -- { "adisen99/codeschool.nvim", enabled = true },
  -- { "bluz71/vim-moonfly-colors", enabled = true },
  -- { "bluz71/vim-nightfly-colors", enabled = true },
  -- { "catppuccin/nvim", enabled = true },
  -- { "cpea2506/one_monokai.nvim", enabled = true },
  -- { "dasupradyumna/midnight.nvim", enabled = true },
  -- { "fenetikm/falcon", enabled = true },
  -- { "folke/tokyonight.nvim", enabled = true },
  -- { "ishan9299/modus-theme-vim", enabled = true },
  -- { "jim-at-jibba/ariake-vim-colors", enabled = true },
  -- { "kaiuri/nvim-juliana", enabled = true },
  -- { "kdheepak/monochrome.nvim", enabled = true },
  -- { "kvrohit/mellow.nvim", enabled = true },
  -- { "kvrohit/rasmus.nvim", enabled = true },
  -- { "kvrohit/substrata.nvim", enabled = true },
  -- { "kyazdani42/blue-moon", enabled = true },
  -- { "ldelossa/vimdark", enabled = true },
  -- { "lmburns/kimbox", enabled = true },
  -- { "lourenci/github-colors", enabled = true },
  -- { "luisiacc/gruvbox-baby", enabled = true },
  -- { "marko-cerovac/material.nvim", enabled = true },
  -- { "maxmx03/FluoroMachine.nvim", enabled = true },
  -- { "mhartington/oceanic-next", enabled = true },
  -- { "navarasu/onedark.nvim", enabled = true },
  -- { "neanias/everforest-nvim", enabled = true },
  -- { "nxvu699134/vn-night.nvim", enabled = true },
  -- { "nyngwang/nvimgelion", enabled = true },
  -- { "nyoom-engineering/oxocarbon.nvim", enabled = true },
  -- { "ofirgall/ofirkai.nvim", enabled = true },
  -- { "olimorris/onedarkpro.nvim", enabled = true },
  -- { "olivercederborg/poimandres.nvim", enabled = true },
  -- { "phha/zenburn.nvim", enabled = true },
  -- { "projekt0n/github-nvim-theme", enabled = true },
  -- { "ramojus/mellifluous.nvim", enabled = true },
  -- { "ray-x/aurora", enabled = true },
  -- { "ray-x/starry.nvim", enabled = true },
  -- { "rebelot/kanagawa.nvim", enabled = true },
  -- { "rmehri01/onenord.nvim", enabled = true },
  -- { "rockerBOO/boo-colorscheme-nvim", enabled = true },
  -- { "rockyzhang24/arctic.nvim", enabled = true },
  -- { "sainnhe/edge", enabled = true },
  -- { "sainnhe/everforest", enabled = true },
  -- { "sainnhe/sonokai", enabled = true },
  -- { "savq/melange-nvim", enabled = true },
  -- { "sekke276/dark_flat.nvim", enabled = true },
  -- { "shaunsingh/moonlight.nvim", enabled = true },
  -- { "sonjiku/yawnc.nvim", enabled = true },
  -- { "tanvirtin/monokai.nvim", enabled = true },
  -- { "theniceboy/nvim-deus", enabled = true },
  -- { "tiagovla/tokyodark.nvim", enabled = true },
  -- { "yashguptaz/calvera-dark.nvim", enabled = true },
  -- { "yonlu/omni.vim", enabled = true },
  -- { "zootedb0t/citruszest.nvim", enabled = true },
}
